name: Upload React App

on:
  push:
    branches:
    - main
    
jobs:
  build-and-deploy-app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checking out code
        uses: actions/checkout@main
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: npm run build
        env:
          REACT_APP_BACKEND_HOST: ${{ secrets.SPRING_BOOT }}
          CI: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
