name: Upload React App

on:
  push:
    branches:
    - main
    
jobs:
  build-and-deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@main
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: npm run build
        env:
          REACT_APP_BACKEND_HOST: ${{ secrets.SPRING_BOOT }}
          CI: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ s3://dental-clinic-app --delete
